kind: pipeline
name: deploy

steps:

  - name: test
    image: alpine:3.13
    environment:
      TERRAFORM: 0.14.7
      TERRAGRUNT: 0.28.24
    commands:
      - apk add --no-cache curl

      - mkdir bin
      - export PATH=$${PATH}:$${PWD}/bin
      - curl --silent -O https://releases.hashicorp.com/terraform/$${TERRAFORM}/terraform_$${TERRAFORM}_linux_amd64.zip
      - unzip terraform_$${TERRAFORM}_linux_amd64.zip
      - chmod +x terraform
      - mv terraform bin/

      - curl --silent -L -O https://github.com/gruntwork-io/terragrunt/releases/download/v$${TERRAGRUNT}/terragrunt_linux_amd64
      - chmod +x terragrunt_linux_amd64
      - mv terragrunt_linux_amd64 bin/terragrunt

      - terraform --version
      - terragrunt --version
    when:
      branch: master
      event: push


