kind: pipeline
name: deploy

steps:

  - name: test
    image: alpine:3.13
    environment:
      TERRAFORM: 0.14.7
    commands:
      - apk add --no-cache curl
      - mkdir bin
      - export PATH=$${PATH}:$${PWD}/bin
      - curl --silent -O https://releases.hashicorp.com/terraform/$${TERRAFORM}/terraform_$${TERRAFORM}_linux_amd64.zip
      - unzip terraform_$${TERRAFORM}_linux_amd64.zip
      - chmod +x terraform
      - mv terraform bin/
      - terraform --version
    when:
      branch: master
      event: push


