
kind: pipeline
name: deploy

steps:
  - name: Install dependencies
    image: *alpine_image
    environment:
      terraform_version:
      terragrunt_version:
    commands:
      - mkdir bin
      - "export PATH=${'$'}PATH:${'$'}PWD/bin"

      - curl --silent -O https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip
      - unzip terraform_${terraform_version}_linux_amd64.zip
      - chmod +x terraform
      - mv terraform bin/

      # - curl --silent -L -O %artifactory_url%/terragrunt-generic-remote/v%terragrunt_version%/terragrunt_linux_amd64
      # - chmod +x terragrunt_linux_amd64
      # - mv terragrunt_linux_amd64 bin/terragrunt

      - terraform --version
      # - terragrunt --version
    when:
      branch: master
      event: push
